config/routes.rb
Picket::Application.routes.draw do
  get "/profile" => 'user#index'
  post "/profile" => 'user#update'

  devise_for :users, :skip => :registrations

  resources :sites
  root :to => 'sites#index'
  
  
  if Rails.env.development?
    require 'resque/server'
    mount Resque::Server.new, :at => "/resque"
  end
  
end

app/models/site.rb
require 'transitions'

class Site
  include Mongoid::Document
  include Mongoid::Timestamps
  include ActiveRecord::Transitions
  
  attr_accessible :url
  
  field :url, :type => String
  field :state, :type => String, :default => "unknown"
  field :message, :type => String, :default => ""

  field :content_validate_type, :type => Boolean, :default => nil
  field :content_validate_text, :type => String, :default => ""

  field :ok_at, :type => DateTime
  field :failed_at, :type => DateTime

  belongs_to :user

  validates_presence_of :url
  validates_format_of :url, :with => %r{^http\://[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,3}(/\S*)?$}

  state_machine do
    state :unknown
    state :ok
    state :failed
    
    event :ok, :timestamp => true do
      transitions :from => [:ok, :failed, :unknown], :to => :ok
    end

    event :failed, :timestamp => true do
      transitions :from => [:ok, :failed, :unknown], :to => :failed      
    end
    
    event :reset do
      transitions :from => [:ok, :failed, :unknown], :to => :unknown
    end
  end
end

app/models/site_watcher.rb
class SiteWatcher
  include SitesHelper
  
	def initialize(site)
    @site = site
    @http_timeout = Settings.http_timeout
  end
  
  def watch
    response = get_url(@site.url)

    if response.success?
      if content_valid?(response.body)
        @site.ok!
      else
        @site.failed!
        @site.message = "Validation fail: #{validation_description(@site)}"
      end
    elsif response.timed_out?
      @site.failed!
      @site.message = "Could not get a response from the server before timing out (#{@http_timeout} seconds)."
    elsif response.code == 0
      @site.failed!
      @site.message = "Could not get an http response, something's wrong."    
    else
      @site.failed!
      @site.message = "Server returned: #{response.code.to_s} #{response.status_message}"
    end

    @site.state
  end
  
  private
  def content_valid?(content)
    return true if @site.content_validate_text.empty?
    return true if @site.content_validate_type.nil?
    return true if @site.content_validate_type && content.include?(@site.content_validate_text)
    return true if !@site.content_validate_type && !content.include?(@site.content_validate_text)
    return false
  end

  def get_url(url)
    request = Typhoeus::Request.new(url, :method => :get, :timeout => @http_timeout * 1000, :follow_location => true)
    hydra = Typhoeus::Hydra.hydra
    hydra.queue(request)
    hydra.run
    request.response    
  end
end

app/models/user.rb
class User
  include Mongoid::Document

  attr_accessible :email, :password

  # Include default devise modules. Others available are:
  # :registerable, :recoverable, :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :null => false, :default => ""
  field :encrypted_password, :type => String, :null => false, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  has_many :sites

  ## Encryptable
  # field :password_salt, :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :load_site, :except => [:index, :new, :create]
  before_filter :required_owner!, :except => [:index, :new, :create]

  # GET /sites
  # GET /sites.json
  def index
    @sites = current_user.sites

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @sites }
    end
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/new
  # GET /sites/new.json
  def new
    @site = Site.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @site }
    end
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(params[:site])
    @site.user = current_user

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render json: @site, status: :created, location: @site }
      else
        format.html { render action: "new" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /sites/1
  # PUT /sites/1.json
  def update
    if params[:site][:url] != @site.url
      @site.reset! 
      Resque.enqueue(SiteChecker, @site.id.to_s)
    end

    respond_to do |format|
      if @site.update_attributes(params[:site])
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy

    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end
  
  private
  def load_site
    @site = current_user.sites.find(params[:id])
  end

  def required_owner!
    if @site.user_id != current_user.id
      render :nothing => true, :status => :forbidden
    end
  end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!

  def index
    @user = current_user
  end
  
  def update
    @user = User.find(current_user.id)
  
    if params[:user][:password].empty? && params[:user][:password_confirmation].empty?
      if @user.update_without_password(params[:user])
        sign_in @user, :bypass => true
        flash[:notice] = "User profile updated"
      else
        flash[:error] = "Error updating password"
      end
    
    else
      if @user.update_attributes(params[:user])
        sign_in @user, :bypass => true
        flash[:notice] = "User profile updated"
      else
        flash[:error] = "Error updating password"
      end
    end

    redirect_to profile_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_authentication
    if user_signed_in?
      link_to('Logout', destroy_user_session_path, :method => :delete)
    else
      link_to('Login', new_user_session_path)
    end
  end
end

app/helpers/sites_helper.rb
module SitesHelper
  include ActionView::Helpers::DateHelper 

  def icon_for_site(site)
    case site.state
    when "unknown"
      image_tag("icons/help.png")
    when "ok"
      image_tag("icons/accept.png")
    when "failed"
      image_tag("icons/exclamation.png")
    else
      raise "unexpected state: #{site.state}"
    end
  end

  def message_for_site(site)
    site_name = site.url.gsub(%r{^http://}, "")

    case site.state
    when "unknown"
      "#{site_name} will be watched soon"
    when "ok"
      "#{site_name} is running"
    when "failed"
      time_change = time_ago_in_words(site.failed_at)
      "#{site_name} is down since #{time_change} ago"
    else
      raise "unexpected state: #{site.state}"
    end
  end
  
  def validation_description(site)
    if site.content_validate_type
      "Contains \"#{site.content_validate_text}\""
    else
      "Doesn't contains \"#{site.content_validate_text}\""
    end
  end
  
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/application/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success">
  <a class="close">×</a>
  <p class="error"><%= flash[:notice] %></p>
  </div>
<% end %>
<% if flash[:error] %>
  <div class="alert alert-error">
  <a class="close">×</a>
  <p class="error"><%= flash[:error] %></p>
  </div>
<% end %>

app/views/application/_loggedin_nav_bar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
      <div class="container">
      <a class="brand" href="#">Picket</a>
      <div class="container nav-collapse">
        <ul class="nav pull-right">
          <li><%= link_to "Profile", profile_path %></li>
          <li><%= link_to('Logout', destroy_user_session_path, :method => :delete) %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/application/_nav_bar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
      <div class="container">
      <a class="brand" href="#">Picket</a>
      <div class="container nav-collapse">
        <ul class="nav pull-right">
          <li><%= link_to('Login', new_user_session_path) %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Picket</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <!-- Le styles -->
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <style>
      body {
        padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */
      }
    </style>

    <!-- Le fav and touch icons -->
    <link href="images/favicon.ico" rel="shortcut icon">
    <link href="images/apple-touch-icon.png" rel="apple-touch-icon">
    <link href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72">
    <link href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114">
  </head>
  <body>
    <% if user_signed_in? %>
      <%= render :partial => 'loggedin_nav_bar' %>
    <% else %>
      <%= render :partial => 'nav_bar' %>
    <% end %>

    <div class="container">
      <div class="content">
        <div class="row">
          <div class="span9">
            <%= render :partial => 'flash', :locals => {:flash => flash}%>
            <%= yield %>
          </div>

          <div class="span1">&nbsp;</div>

          <div class="span3">
            <%= yield :sidebar %>
          </div>
        </div>
      </div>

      <footer>
        <p></p>
      </footer>

    </div> <!-- /container -->

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/sites/_form.html.erb
<%= simple_form_for @site do |f| %>
	<%= f.input :url, :placeholder => 'http://', :label => 'make sure this site is up:', 
		:input_html => { :class => 'span6' } %>
	
	<%= f.input :content_validate_type, 
		:as => :radio_buttons, 
		:collection => [[true, "Contains:"], [false, "Doesn't contains:"]], 
		:label_method => "last", :value_method => "first", 
		:label => "and", :wrapper_class => "contains" %>
		
	<%= f.input :content_validate_text, :label => "", :wrapper_class => "validate_text", 
		:placeholder => 'Optional. Select from above to activate.',
		:input_html => { :class => 'span6' } %>

  <%= f.button :submit %>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<div>
  <a class="btn btn-primary" id="action-btn">
    <i class="icon-plus-sign icon-white"></i>
    Add
  </a>
  <h1>Your sites</h1>
</div>

<table class="table" id="sites-table">
<% @sites.each do |site| %>
  <tr>
    <td class="span7 description">
			<%= icon_for_site(site)%> <%= message_for_site(site) %> 
			<small><%= site.failed? ? site.message : "" %></small>
		</td>
    <td class="span2">
      <span class="actions">
      <%= link_to 'Edit', edit_site_path(site) %> 
      <%= link_to 'Destroy', site, confirm: 'Are you sure?', method: :delete %>
      </span>
    </td>
  </tr>
<% end %>
</table>

app/views/sites/new.html.erb
<h1>Add Site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Url:</b>
  <%= @site.url %>
</p>

<p>
  <b>Status:</b>
  <%= @site.state %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>

app/views/user/index.html.erb
<h3>Profile</h3>

<%= simple_form_for @user, :url => profile_path, :method => :post do |f| %>
  <%= f.input :email %>  
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.button :submit %>
<% end %>